[package]
name = "zos-cics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "CICS transaction processing for zOS-clone"

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json = "1"
zos-dataset = { path = "../zos-dataset" }

[dev-dependencies]
