[package]
name = "open-mainframe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "OpenMainframe CLI â€” COBOL interpreter with CICS TUI"

[[bin]]
name = "open-mainframe"
path = "src/main.rs"

[dependencies]
open-mainframe-cobol.workspace = true
open-mainframe-runtime.workspace = true
open-mainframe-cics.workspace = true
open-mainframe-tui.workspace = true
open-mainframe-precompilers.workspace = true

clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
