[package]
name = "open-mainframe-uss"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "z/OS UNIX System Services (USS) & POSIX"

[dependencies]
thiserror.workspace = true
miette.workspace = true
