apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zos-clone.fullname" . }}-secrets
  labels:
    {{- include "zos-clone.labels" . | nindent 4 }}
type: Opaque
stringData:
  database_url: {{ include "zos-clone.databaseUrl" . | quote }}
