[package]
name = "zos-clone"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for the zOS-clone mainframe emulator"

[[bin]]
name = "zos-clone"
path = "src/main.rs"

[features]
default = []
llvm = ["zos-cobol/llvm", "dep:inkwell"]

[dependencies]
inkwell = { workspace = true, optional = true }
clap.workspace = true
clap_complete.workspace = true
dirs.workspace = true
miette.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zos-encoding.workspace = true
zos-runtime.workspace = true
zos-dataset.workspace = true
zos-cobol.workspace = true
zos-jcl.workspace = true

[dev-dependencies]
