[package]
name = "zos-jcl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "JCL interpreter for zOS-clone"

[dependencies]
miette.workspace = true
thiserror.workspace = true
zos-dataset.workspace = true
zos-sort.workspace = true

[dev-dependencies]
